Bookers1/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root :to => 'books#top'
end

Bookers1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers1/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

Bookers1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      @books = Book.all
      render "index"
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render "edit"  
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to book, notice: 'Book was successfully destroyed.'
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers1/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers1/app/helpers/books_helper.rb
module BooksHelper
end

Bookers1/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
    <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<strong>|</strong>
<%= link_to "Back", books_path %>

Bookers1/app/views/books/index.html.erb
<body>
<p id="notice"><%= notice %></p>
<h1>Books</h1>
<table>
  <thead>
    <tr class="index-heading">
      <th class="index-title">Title</th>
      <th class="index-body">Body</th>
      <th class="index-space" colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>


<%= form_with model:@book, local:true do |f| %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のerrorが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
<br>
<%= f.submit 'Create Book' %>
<% end %>


</body>

Bookers1/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<p class="show-box">
<strong>Title:</strong>
<%= @book.title %>
</p>
<p class="show-box">
<strong>Body:</strong>
<%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<strong>|</strong>
<%= link_to "Back", books_path %>

Bookers1/app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>印象を共有し交換することができます。</p>
<%= link_to "Start", books_path %>

Bookers1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>